application: hagglecommunitydev
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- warmup

handlers:

- url: /_ah/warmup
  script: warmup_requests.app
  secure: always

######################### REST ENDPOINTS #########################

- url: /api/members/.*
  script: handlers.rest.members.app
  secure: never

- url: /api/events/.*
  script: handlers.rest.events.app
  secure: never

- url: /api/common/.*
  script: handlers.rest.common.app
  secure: never

######################### STATIC ENDPOINTS #########################

- url: /assets/css
  static_dir: assets/css
  secure: never

- url: /assets/js
  static_dir: assets/js
  secure: never

- url: /assets/img
  static_dir: assets/img
  secure: never

- url: /assets/fonts
  static_dir: assets/fonts
  secure: never

- url: /assets/txt
  static_dir: assets/txt
  secure: always

- url: /5ab8a7c4fa38692e2fbbee4b1b8c9ddd\.txt
  static_files: assets/txt/5ab8a7c4fa38692e2fbbee4b1b8c9ddd.txt
  upload: assets/txt/5ab8a7c4fa38692e2fbbee4b1b8c9ddd\.txt

######################### WEB ENDPOINTS #########################

- url: /members/.*
  script: handlers.web.members.app
  secure: never

- url: /manager/.*
  script: handlers.web.managers.app

- url: /candidate/.*
  script: handlers.web.candidates.app

- url: /tracks
  script: handlers.web.tracks.app
  secure: never

- url: /.*
  script: handlers.web.app
  secure: never

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
