application: hagglecommunitydev
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

handlers:

- url: /api/members/.*
  script: handlers.rest.members.app
  secure: always

- url: /members/.*
  script: handlers.web.members.app
  secure: always

- url: /
  script: handlers.web.index.app
  secure: always

- url: /testspy
  script: handlers.web.index.app
  secure: always

- url: /calendar
  script: handlers.web.index.app
  secure: always

- url: /member_registration
  script: handlers.web.index.app
  secure: always

- url: /member_access
  script: handlers.web.index.app
  secure: always

- url: /member_profile
  script: handlers.web.index.app
  secure: always

- url: /member_access_question
  script: handlers.web.index.app
  secure: always

- url: /accept_contact
  script: handlers.web.index.app
  secure: always

- url: /validate_access_code
  script: handlers.web.index.app
  secure: always

######################### STATIC ENDPOINTS #########################

- url: /assets/css
  static_dir: assets/css
  secure: always

- url: /assets/js
  static_dir: assets/js
  secure: always

- url: /assets/img
  static_dir: assets/img
  secure: always

- url: /assets/fonts
  static_dir: assets/fonts
  secure: always

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'